### ISSUE TITLE
What If all my functions have the right type and pass all of my tests?

### ISSUE THREAD

**Issue by vanh17** [skiadas/ProgLangAssignments#2]
Dear Dr. @Skiadas
can I submit now or have to create post more issues :-?
I have some doubts that I will not get the full point for creating issues this time, since it has been only 3 issues so far

**Comment by skiadas** [comment]
You should have created a separate issue for each problem as you worked on them. And a separate issue for writing tests for those problems. It's a bit late now.

**Comment by vanh17** [comment]
:)) Okay,
It is never too late to study sir. I will just add more tests and add more issues to run those test though
Thank you Dr.  @skiadas
